In [26]:
from sklearn.datasets import load_diabetes

import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score
from sklearn.model_selection import train_test_split

In [27]:
X,y = load_diabetes(return_X_y=True)

In [28]:
print(X.shape)
print(y.shape)

(442, 10)
(442,)


In [29]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=2)

In [30]:
reg = LinearRegression()
reg.fit(X_train,y_train)

LinearRegression()

In [31]:
print(reg.coef_)
print(reg.intercept_)

[  -9.15865318 -205.45432163  516.69374454  340.61999905 -895.5520019
  561.22067904  153.89310954  126.73139688  861.12700152   52.42112238]
151.88331005254167


In [32]:
y_pred = reg.predict(X_test)
r2_score(y_test,y_pred)

0.4399338661568968

In [35]:
class GDRegressor:
    def __init__(self,learning_rate=0.01,epochs=100) -> None:
        self.learning_rate=learning_rate
        self.epochs=epochs

        self.intercept_=None
        self.coef_=None
    
    def fit(self,X_train,y_train):
        #intilize intercept and coefficent
        self.intercept_=0
        self.coef_=np.ones(X_train.shape[1])

        for i in range(self.epochs):

            y_hat=np.dot(X_train,self.coef_)+self.intercept_
            intercept_der=-2*np.mean(y_train-y_hat)
            self.intercept_=self.intercept_-(self.learning_rate*(intercept_der))

            coef_dev=-2*np.dot((y_train-y_hat),X_train)/X_train.shape[0]
            self.coef_=self.coef_-(self.learning_rate*(coef_dev))

        return self.intercept_,self.coef_
    
    def predict(self,X_test):
        y_pred=np.dot(X_test,self.coef_)+self.intercept_
        return y_pred

In [36]:
model=GDRegressor(epochs=1000)

In [37]:
model.fit(X_train,y_train)

(150.7529235828462,
 array([ 15.98156223,   3.59524752,  41.65671073,  32.55163341,
         14.77244856,  11.42882105, -24.66648529,  27.6427229 ,
         41.18745291,  25.180466  ]))

# Comparing Result of Both the Models

In [43]:
model.predict(X_test)

array([151.69008229, 157.25528777, 150.31793901, 143.76477242,
       164.11872493, 162.92398083, 141.67672222, 143.64250532,
       139.64095147, 156.31214192, 155.00032765, 154.02105454,
       157.10971539, 153.28040411, 163.3135349 , 141.56012318,
       154.57075573, 146.62870554, 149.73946656, 149.56149625,
       144.43373582, 161.27483367, 156.02392608, 156.36599207,
       146.16290259, 162.51831299, 157.31255453, 148.87883554,
       136.33916258, 167.8714153 , 165.21440917, 145.96864539,
       138.11981527, 145.72452497, 158.61501747, 153.88249987,
       154.43542838, 159.52019389, 144.64186906, 164.33558843,
       146.70669061, 147.19704943, 156.83662102, 156.8263246 ,
       153.09239475, 150.16474228, 155.02898377, 169.95047887,
       146.27729108, 161.10701691, 162.82292598, 144.65855705,
       147.78530375, 154.32670093, 157.22600477, 146.60542966,
       155.86365781, 140.55652051, 151.89913761, 147.29632307,
       153.01288245, 156.03079784, 145.01669933, 157.00

In [42]:
reg.predict(X_test)

array([154.1213881 , 204.81835118, 124.93755353, 106.08950893,
       258.5348576 , 256.3310074 , 118.75087616, 119.52440696,
       101.50816735, 190.54048661, 141.70656811, 172.51883961,
       174.33861649, 134.80942706, 294.13994537,  94.11798038,
       211.97059795, 156.49579378, 134.21000428, 119.62664644,
       148.87842251, 165.00873409, 151.10021038, 176.04063756,
       133.27769647, 221.29555392, 197.17324941,  96.1577688 ,
        50.26012711, 230.48580317, 242.06073866, 114.11129218,
        67.07532417,  94.52943825, 201.21415375, 167.05136201,
       159.881268  , 192.78746659, 114.49551325, 233.48234551,
       140.82563045, 121.0680409 , 192.27480772, 191.12738845,
       179.16865788, 148.34935601, 163.47414622, 276.81647884,
       100.17926432, 164.10555298, 255.80762189, 136.9466204 ,
       152.37503699, 107.92237882, 194.21924678,  77.34670792,
       118.50482479,  68.38335763, 154.29258529, 162.48840259,
       168.36788326, 156.87790322,  97.14191797, 238.16